export const postData = [
  {
    title: "Standard /llms.txt",
    url: "/es/posts/ai-llms-txt",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_ai-llms-txt-cover.avif",
    lang: "es",
    isPublished: true,
  },
  {
    title: "Variables de Entorno",
    url: "/es/posts/config-env-files",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_config-env-files-cover.avif",
    lang: "es",
    isPublished: true,
  },
  {
    title: "Archivos .ARB",
    url: "/es/posts/flutter-arb-files",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_flutter-arb-files-cover.avif",
    lang: "es",
    isPublished: true,
  },
  {
    title: "Formato TOON",
    url: "/es/posts/formats-toon",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_formats-toon-cover.avif",
    lang: "es",
    isPublished: true,
  },
  {
    title: "Anatomía URL",
    url: "/es/posts/url-anatomy",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_url-anatomy-cover.avif",
    lang: "es",
    isPublished: true,
  },
  {
    title: "HTTP Request",
    url: "/es/posts/formats-http-request",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_formats-http-request-cover.avif",
    lang: "es",
    isPublished: true,
  },
  {
    title: "IEEE 754 Anatomy",
    url: "/es/posts/ieee754-anatomy",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_ieee754-anatomy-cover.avif",
    lang: "es",
    isPublished: true,
  },
  {
    title: "IEEE 754 Special",
    url: "/es/posts/ieee754-special",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_ieee754-anatomy-cover.avif",
    lang: "es",
    isPublished: true,
  },
  {
    title: "Git Commit Anatomy",
    url: "/es/posts/git-commit-anatomy",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_git-commit-anatomy-cover.avif",
    lang: "es",
    isPublished: true,
  },
  {
    title: "Git Commit Cheatsheet",
    url: "/es/posts/git-commit-cheatsheet",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_git-commit-anatomy-cover.avif",
    lang: "es",
    isPublished: true,
  },
  {
    title: "5 Antipatrones",
    url: "/es/posts/software-anti-patterns",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_software-anti-patterns-cover.avif",
    lang: "es",
    isPublished: true,
  },
  {
    title: "i18n vs l10n",
    url: "/es/posts/software-i18n-vs-l10n",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_software-i18n-vs-l10n-cover.avif",
    lang: "es",
    isPublished: true,
  },
  {
    title: "JWT Anatomy",
    url: "/es/posts/jwt-anatomy",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_jwt-anatomy-cover.avif",
    lang: "es",
    isPublished: true,
  },
  {
    title: "SemVer: x.y.z",
    url: "/es/posts/software-semver",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_software-semver-cover.avif",
    lang: "es",
    isPublished: true,
  },
  {
    title: "Permisos Linux: 755",
    url: "/es/posts/linux-permissions",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_url-anatomy-cover.avif",
    lang: "es",
  },
  {
    title: "IPv4: 192.168.0.1",
    url: "/es/posts/ipv4-anatomy",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_url-anatomy-cover.avif",
    lang: "es",
  },
  {
    title: "Block vs Inline Elements",
    url: "/es/posts/html-block-vs-inline",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_url-anatomy-cover.avif",
    lang: "es",
  },
  {
    title: "Protocolo OsmAnd JSON",
    url: "/es/posts/protocol-osmand-json",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_url-anatomy-cover.avif",
    lang: "es",
  },
  {
    title: "Protocolo OsmAnd URL",
    url: "/es/posts/protocol-osmand-query",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_url-anatomy-cover.avif",
    lang: "es",
  },
  {
    title: "HTTP/2 Framing",
    url: "/es/posts/http2-framing",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_formats-http-request-cover.avif",
    lang: "es",
  },
  {
    title: "HTTP/2 Layers",
    url: "/es/posts/http2-layers",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_config-env-files-cover.avif",
    lang: "es",
  },
  {
    title: "Lex Anatomy (.l)",
    url: "/es/posts/compiler-lex-anatomy",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_config-env-files-cover.avif",
    lang: "es",
  },
  {
    title: "Yacc Anatomy (.y)",
    url: "/es/posts/compiler-yacc-anatomy",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_config-env-files-cover.avif",
    lang: "es",
  },
  {
    title: "AWK: Procesamiento de Texto",
    url: "/es/posts/linux-awk-anatomy",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_url-anatomy-cover.avif",
    lang: "es",
  },
  {
    title: "Python: Walrus Operator :=",
    url: "/es/posts/python-walrus",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_config-env-files-cover.avif",
    lang: "es",
  },
  {
    title: "Python: Métodos Mágicos",
    url: "/es/posts/python-dunder-methods",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_config-env-files-cover.avif",
    lang: "es",
  },
  {
    title: "Operaciones Bitwise",
    url: "/es/posts/bitwise-operations",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_ieee754-anatomy-cover.avif",
    lang: "es",
  },
  {
    title: "Movimiento Browniano",
    url: "/es/posts/algo-brownian-motion",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_url-anatomy-cover.avif",
    lang: "es",
  },
  {
    title: "Linux: Standard Streams",
    url: "/es/posts/linux-standard-streams",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_url-anatomy-cover.avif",
    lang: "es",
  },
  {
    title: "Cron Syntax: Automatización",
    url: "/es/posts/linux-cron-syntax",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_config-env-files-cover.avif",
    lang: "es",
  },
  {
    title: "Hashing vs. Cifrado",
    url: "/es/posts/software-hashing-vs-encryption",
    image: "/images/optimized/posts/127.0.0.1_8000_es_posts_jwt-anatomy-cover.avif",
    lang: "es",
  },
];
