export const projectData = [
  {
    title: "Calendario de Adviento Interactivo",
    slug: "interactive-advent-calendar",
    description:
      "Crea un calendario de adviento digital en React con animaciones y diseño festivo. Permite abrir cajas según el día correspondiente revelando mensajes o regalos virtuales.",
    shortDescription: "Calendario de adviento digital interactivo en React.",
    githubLink: "https://github.com/xeland314/advent-calendar",
    demoLink: "https://xeland314.github.io/advent-calendar/",
    tags: ["React", "Frontend", "PixelArt", "TailwindCSS"],
    image: "/images/optimized/projects/advent_calendar/card.avif",
    isFeatured: false,
  },
  {
    title: "Tetris",
    slug: "tetris",
    description:
      "Un clásico juego de Tetris desarrollado en Java utilizando Swing. Este proyecto incluye características como niveles de dificultad, puntuaciones y una interfaz gráfica intuitiva.",
    shortDescription: "Juego de Tetris en Java con Swing.",
    githubLink: "https://github.com/xeland314/PoliTetris",
    demoLink: "https://github.com/xeland314/PoliTetris/releases",
    tags: ["Java", "Swing"],
    image: "/images/optimized/projects/tetris/card.avif",
  },
  {
    title: "Chat Analyzer",
    slug: "chat-analyzer",
    description:
      "Una herramienta de análisis de chats de WhatsApp desarrollada en Dart/Flutter y Rust. Disponible en Windows, Linux y Android. Provee una interfaz sencilla para entender la interacción de un grupo de WhatsApp, estadísticas por usuario y análsis de sentimientos. Todo de manera local sin enviar datos fuera de tu dispositivo. Puedes analizar hasta 100000 mensajes en menos de 10 segundos.",
    shortDescription: "Analiza chats de WhatsApp en cualquier dispositivo",
    githubLink: "https://github.com/xeland314/chat_analyzer_ui",
    demoLink: "https://xeland314.github.io/chat_analyzer_ui/",
    tags: ["WhatsApp", "Dart", "Flutter", "Rust", "Multiplataforma"],
    image: "/assets/chat_analyzer_logo_app.jpg",
    isFeatured: true,
  },
  {
    title: "Memory Game",
    slug: "memory-game",
    description:
      "Un juego de memoria interactivo creado con HTML, CSS y JavaScript. Desafía a los jugadores a encontrar pares de cartas en el menor tiempo posible.",
    shortDescription: "Juego de memoria con HTML, CSS y JS.",
    githubLink: "https://github.com/xeland314/memory-game",
    demoLink: "https://xeland314.github.io/memory-game/",
    tags: ["Html", "Css", "JavaScript"],
    image: "/images/optimized/projects/memorygame/card.avif",
  },
  {
    title: "Encriptador de Texto",
    slug: "text-encryptor",
    description:
      "Proyecto desarrollado como parte del reto Alura Latam. Este encriptador de texto permite cifrar y descifrar mensajes utilizando técnicas básicas de criptografía.",
    shortDescription: "Reto Alura Latam: Encriptador de texto.",
    githubLink: "https://github.com/xeland314/encriptador-de-texto",
    demoLink: "https://xeland314.github.io/encriptador-de-texto/",
    tags: ["Html", "Css", "JavaScript"],
    image: "/images/optimized/projects/encriptador/card.avif",
  },
  {
    title: "Analizador-lexico",
    slug: "lexical-analyzer",
    description:
      "Un analizador léxico que reconoce y recupera errores en las distintas etapas de compilación. Este proyecto destaca por su uso de expresiones regulares para reconocer sistemas numéricos, operadores aritméticos y funciones matemáticas.",
    shortDescription: "Analizador léxico para sistemas numéricos y operadores.",
    githubLink: "https://github.com/xeland314/Analizador-lexico",
    tags: ["C", "Compiladores", "Expresiones Regulares", "Golang"],
    image: "/images/optimized/projects/analizador-lexico/card.avif",
  },
  {
    title: "SpeedTest",
    slug: "speedtest",
    description:
      "Un script en Bash para medir el tiempo de ejecución de cualquier programa en Linux. Utiliza 'time' y 'awk' para calcular el tiempo real, de usuario y de sistema, además de la desviación estándar.",
    shortDescription: "Script en Bash para pruebas de velocidad en Linux.",
    githubLink: "https://github.com/xeland314/speedtest",
    tags: ["Bash", "Performance", "Awk"],
    image: undefined,
  },
  {
    title: "freqtables",
    slug: "freqtables",
    description:
      "Un paquete en Python para crear tablas de frecuencias simples e intervalos. Permite inicializar tablas con listas, tuplas o diccionarios y calcular estadísticas descriptivas.",
    shortDescription: "Paquete en Python para tablas de frecuencias.",
    githubLink: "https://github.com/xeland314/freqtables",
    tags: ["Python", "Estadisticas", "TablasDeFrecuencias"],
    image: "/images/optimized/projects/freqtables/card.avif",
  },
  {
    title: "objects-in-C",
    slug: "objects-in-c",
    description:
      "Un proyecto basado en el libro 'Object-oriented Programming with Ansi-C' de Axel-Tobias Schreiner. Implementa conceptos de programación orientada a objetos en C, como encapsulamiento y herencia.",
    shortDescription: "Programación orientada a objetos en C.",
    githubLink: "https://github.com/xeland314/objects-in-C",
    tags: ["C", "Oop", "Encapsulamiento", "Strings"],
    image: undefined,
  },
  {
    title: "Conversor de Unidades",
    slug: "unit-converter",
    description:
      "Un conversor de unidades desarrollado para el Challenge #2 de Oracle Next Education. Permite convertir entre diferentes unidades de longitud, tiempo, temperatura y divisas con una interfaz gráfica sencilla.",
    shortDescription: "Conversor de unidades con interfaz gráfica en Java.",
    githubLink: "https://github.com/xeland314/conversor-de-unidades",
    tags: ["Java", "Swing", "Conversion De Unidades"],
    image: "/images/optimized/projects/conversor-de-unidades/card.avif",
    isFeatured: false,
  },
  {
    title: "Simplex Solver",
    slug: "simplex",
    description:
      "Herramienta integral para Programación Lineal con múltiples interfaces: DSLs (String-based y Pythonic), Command-Line, y una GUI avanzada con PySide6 que incluye visualización gráfica.",
    shortDescription:
      "Solver completo de Programación Lineal (LP) con DSLs y GUI.",
    githubLink: "https://github.com/xeland314/simplex",
    demoLink: "https://github.com/xeland314/simplex/releases",
    tags: ["Python", "Optimizacion", "Simplex", "DSLs", "PySide6", "GUI"],
    image:
      "/images/optimized/projects/simplex/card.avif",
    isFeatured: true,
  },
  {
    title: "Buscador de Ubicaciones - Ecuador",
    slug: "autocompleter",
    description:
      "Un buscador de ubicaciones para Ecuador con autocompletado avanzado. Utiliza un servidor Nominatim local, caché con Redis y un sistema de 'refuerzo' para aprender de las selecciones del usuario y mejorar la relevancia de los resultados.",
    shortDescription: "Buscador de ubicaciones en Ecuador con IA y caché.",
    githubLink: "https://github.com/xeland314/autocompleter",
    tags: ["FastAPI", "Python", "Nominatim", "Redis", "Reinforcement Learning"],
    image: "/images/optimized/projects/autocompleter/card.avif",
    isFeatured: false,
  },
  {
    title: "URL Shortener",
    slug: "urlshortener",
    description:
      "Servicio de acortador de URLs completo y eficiente, construido con Django, Django REST Framework y HTMX. Permite crear URLs públicas, privadas (con token) y protegidas con contraseña, con gestión de usuarios y tareas asíncronas con Celery.",
    shortDescription:
      "Acortador de URLs con Django y diferentes tipos de acceso.",
    githubLink: "https://github.com/xeland314/urlshortener",
    tags: ["Django", "DRF", "Python", "Celery", "HTMX", "Redis"],
    image: "/images/optimized/projects/shortener/card.avif",
    isFeatured: true,
  },
  {
    title: "CodeCraft Estimator",
    slug: "codecraft-estimator",
    description:
      "Estimador de proyectos de software impulsado por IA. La herramienta calcula el tiempo y costo de proyectos, gestiona riesgos y permite el aumento de tareas y módulos, basándose en una fórmula de estimación de tres puntos.",
    shortDescription: "Estimador de proyectos de software con IA (Gemini).",
    githubLink: "https://github.com/xeland314/codecraft-estimator",
    demoLink: "https://codecraft-estimator.vercel.app/",
    tags: ["IA", "TypeScript", "Next.js"],
    image: "/images/optimized/projects/codecraft-estimator/card.avif",
    isFeatured: true,
  },
  {
    title: "Geocoding API",
    slug: "geocoding-api",
    description:
      "Un wrapper de API de geocodificación que integra múltiples servicios (Nominatim, Here, Geoapify) bajo una arquitectura de doble caché. Utiliza Redis para las consultas recientes (cache de corto plazo) y SQLite para el almacenamiento de largo plazo, optimizando el rendimiento y reduciendo las peticiones externas.",
    shortDescription: "Wrapper de geocodificación con doble caché en FastAPI.",
    githubLink: "https://github.com/xeland314/geocoding-api",
    tags: [
      "FastAPI",
      "Python",
      "Geocodificación",
      "Nominatim",
      "Here API",
      "Geoapify",
      "Redis",
      "SQLite",
    ],
    image: "/images/optimized/projects/geocoding-api/card.avif",
    isFeatured: true,
  },
  {
    title: "PostMetrics Pro",
    slug: "post-metrics",
    description: "Plataforma integral de análisis para marcas personales, diseñada para rastrear, visualizar y optimizar el rendimiento en múltiples redes sociales. Combina una arquitectura robusta en Go, un frontend moderno en React con estética Cyberpunk, e inteligencia estratégica potenciada por Google Gemini.",
    shortDescription: "Dashboard de métricas sociales con IA y arquitectura en Go.",
    githubLink: "https://github.com/xeland314/post_metrics",
    tags: ["Go", "React", "SQLite", "IA", "Gemini", "TailwindCSS", "Cyberpunk"],
    image: "/images/post_metrics_showcase.png",
    isFeatured: true,
  },
  {
    title: "C-Slides",
    slug: "slides-c",
    description: "Presentador de diapositivas minimalista y de alto rendimiento escrito en C utilizando X11, Cairo y Pango. Diseñado para renderizar archivos Markdown directamente en pantalla con una estética moderna y profesional. Soporta múltiples lenguajes a través de ports funcionales.",
    shortDescription: "Presentador de diapositivas Markdown minimalista en C.",
    githubLink: "https://github.com/xeland314/slides.c",
    tags: ["C", "X11", "Cairo", "Pango", "Markdown", "High-Performance"],
    image: "/images/slides_c_logo.png",
  },
  {
    title: "StatLens",
    slug: "statlens",
    description: "Explorador de distribuciones estadísticas moderno con 13 modelos de probabilidad (Binomial, Normal, Poisson, Gamma, F, etc.). Incluye gráficas dinámicas con Matplotlib, renderizado de fórmulas LaTeX, calculadora de intervalos y exportación a Excel. Construido con Python 3.12 y PySide6.",
    shortDescription: "Explorador de distribuciones estadísticas con Python y PySide6.",
    githubLink: "https://github.com/xeland314/statlens",
    tags: ["Python", "PySide6", "Matplotlib", "LaTeX", "Estadística"],
    image: "/images/statlens_pixel_cat.png",
  },
  {
    title: "zigfetch",
    slug: "zigfetch",
    description: "Visualizador de información del sistema al estilo neofetch compilado a WebAssembly (WASI). El mismo binario corre de forma nativa en Linux y dentro de una terminal en el navegador, leyendo datos del SO, GPU, RAM y resolución en ambos entornos.",
    shortDescription: "Neofetch en WebAssembly (WASI) y Zig.",
    githubLink: "https://github.com/xeland314/zigfetch",
    tags: ["Zig", "WASM", "WASI", "WebAssembly", "Low-Level"],
    image: "/images/zigfetch_screen1.jpg",
  },
  {
    title: "Code to Video",
    slug: "code-to-video",
    description: "Genera videos animados de código siendo escrito directamente en tu navegador. Ideal para tutoriales y redes sociales. Permite personalizar el lenguaje, el tema y la velocidad de escritura.",
    shortDescription: "Generador de videos de código animados en el navegador.",
    demoLink: "https://xeland314.github.io/code-to-video",
    tags: ["TypeScript", "Canvas", "Video", "Developer Tools"],
    image: undefined,
  },
  {
    title: "Code to Image",
    slug: "code-to-img",
    description: "Convierte tus fragmentos de código en imágenes elegantes con fondos personalizados para compartir en plataformas sociales. Soporta resaltado de sintaxis para múltiples lenguajes.",
    shortDescription: "Convierte código en imágenes elegantes para redes sociales.",
    demoLink: "https://xeland314.github.io/code-to-img",
    tags: ["TypeScript", "Canvas", "Developer Tools", "Social Media"],
    image: undefined,
  },
  {
    title: "¿Puedo usar mi GPU?",
    slug: "can-i-use-gpu",
    description: "Verifica si tu navegador y hardware son compatibles con la aceleración por GPU para aplicaciones Flutter y WebGPU. Proporciona detalles técnicos sobre el renderizador y las capacidades de cómputo disponibles.",
    shortDescription: "Verificador de compatibilidad de GPU y WebGPU.",
    demoLink: "https://xeland314.github.io/can-i-use-gpu",
    tags: ["WebGPU", "Hardware", "Flutter", "Developer Tools"],
    image: undefined,
  },
];
